<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PieLaboratories.Svg</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0.0</Version>
    <IsPackable>true</IsPackable>
    <NuspecFile>PieLaboratories.SvgParser.nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
    <NuspecProperties>version=$(Version);configuration=$(Configuration)</NuspecProperties>
    <PackageOutputPath>$(MSBuildProjectDirectory)/../../../../artifacts/nupkgs</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)/../../../../build/bindings/csharp/native/libsvgparser_c.so"
          Condition="$([MSBuild]::IsOSPlatform('Linux'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libsvgparser_c.so</Link>
    </None>
    <None Include="$(MSBuildProjectDirectory)/../../../../build/bindings/csharp/native/svgparser_c.dll"
          Condition="$([MSBuild]::IsOSPlatform('Windows'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>svgparser_c.dll</Link>
    </None>
    <None Include="$(MSBuildProjectDirectory)/../../../../build/bindings/csharp/native/libsvgparser_c.dylib"
          Condition="$([MSBuild]::IsOSPlatform('OSX'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libsvgparser_c.dylib</Link>
    </None>
  </ItemGroup>

</Project>
